### ISSUE TITLE
Exception when trying to use it on a .jar

### ISSUE THREAD

**Issue by brucardoso2** [nguyenq/tess4j#12] opened 2015-02-12 00:49 UTC
```
Exception in thread "main" java.util.ServiceConfigurationError: javax.imageio.spi.ImageWriterSpi: Provider com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageWriterSpi could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
	at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at net.sourceforge.tess4j.util.ImageIOHelper.getIIOImageList(ImageIOHelper.java:333)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:190)
```

**Comment by nguyenq** [comment] 2015-02-12 02:00
What is the extension of the input file? Make sure filename extension is **.jp2**.

**Comment by brucardoso2** [comment] 2015-02-12 02:03
.png
By the way, how can I build a jar using it as a dependency?

On Thursday, February 12, 2015, Quan Nguyen <notifications@github.com>
wrote:

> What is the extension of the input file? Make sure filename extension is
> *.jp2*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nguyenq/tess4j/issues/12#issuecomment-74004381>.
>


-- 
Bruno Cardoso

**Comment by nguyenq** [comment] 2015-02-12 02:20
The error message indicates it was a jpeg2000 image.

**Comment by brucardoso2** [comment] 2015-02-12 02:54
It works fine when trying to use it as a jar dependency of my program.
How can I encapsulate it inside my program.jar? Any documentatino on it?

**Comment by 4F2E4A2E** [comment] 2015-02-12 12:38
I was not able to reproduce this, you have to provide more information, otherwise we can't reproduce it. Example file? Example Project? What is your scope?

**Comment by 4F2E4A2E** [comment] 2015-02-12 12:43
Some codecs listed [1] may not be registered because the classes can't be instantiated because of missing components.
Please be aware to have compiled and packed your jar files and tess4j project correctly.
It does not seams to be an tess4j issue.

If you agree i will close this issue.

1: http://forums.dcm4che.org/jiveforums/servlet/JiveServlet/download/16-3811-19015-1578/Codecs.txt

**Comment by brucardoso2** [comment] 2015-02-12 14:08
Sorry for the no-context stacktrace paste...

Here are the steps
1. `git clone https://github.com/nguyenq/tess4j.git`
2. `cd tess4j`
3. `mvn clean package` (it will create both shaded and normal jar)
Install the normal jar into local repository 
4. `mvn install:install-file -Dfile=target/tess4j-2.0.0-SNAPSHOT.jar -DpomFile=pom.xml `

I created a simple repository to ease your testing
`git clone https://github.com/brucardoso2/tess4jtest.git`
`mvn clean package` (it will create both shaded and normal jar)

Now run the jar:
`java -jar target/ShadedMaven-1.0-SNAPSHOT-shaded.jar <imagefile>`

**Comment by 4F2E4A2E** [comment] 2015-02-12 16:54
Hah! I knew it, the vendorName classic ;)
It is not tess4j related. The problem is that some jars when packed or merged lost their original vendorName which is needed from some classes or functionalitys like in your case: ImageWriterSpi
The fix is very easy, but it is hard to find the right fix. Basically all you have to set the vendorName in the manifest file inside the jar you are creating.
Let's research this and post the link here.

**Comment by 4F2E4A2E** [comment] 2015-02-12 16:56
Try this one: JAI : how to solve vendorName == null exception https://thierrywasyl.wordpress.com/2009/07/24/jai-how-to-solve-vendorname-null-exception/

**Comment by brucardoso2** [comment] 2015-02-12 18:03
@4F2E4A2E Worked flawlessly :+1:

**Closed** 2015-02-12 18:04 UTC
