### ISSUE TITLE
Unable to set non-English datapath in Tess4J

### ISSUE THREAD

**Issue by sleepybear1113** [nguyenq/tess4j#252] opened 2023-09-23 16:57 UTC
I would like to report an issue regarding setting a non-English datapath in Tess4J. Currently, the library does not support using a datapath with Chinese characters, which limits its usability for users with non-English paths. 

Example：`D:/测试路径/eng.traineddata`, I set dataPath to `D:/测试路径`, it will print
```
Error opening data file D:/测试路径/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

java.lang.Error: Invalid memory access
	at net.sourceforge.tess4j.TessAPI1.TessBaseAPIGetUTF8Text(Native Method)
	at net.sourceforge.tess4j.Tesseract1.getOCRText(Tesseract1.java:512)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:318)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:291)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:272)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:256)
```

when using path `D:/test`, it works.

Is it possible to modify the library's code to support non-English paths, such as setting a datapath with Chinese characters? This would greatly enhance the flexibility and usability of Tess4J for a wider range of users.

[The above content is built using gpt, the original text is from Chinese ]

**Comment by nguyenq** [comment] 2024-01-25 01:32
@sleepybear1113

For our test cases, we set `TESSDATA_PREFIX` environment variable to various values: `D:\Test\tessdata-á`, `D:\Test\tessdata-â`, and `D:\Test\tessdata-ấ`, and run `tesseract --list-langs` command for each. It worked with the first two cases, which use extended ASCII characters, but not with the last one, which contains a Unicode character. Tesseract engine apparently does not support Unicode characters in `tessdata` path.

**Comment by nguyenq** [comment] 2024-01-25 05:14
Duplicate of Issue #190

**Closed** 2024-03-02 19:09 UTC
