### ISSUE TITLE
When using Tesseract, there is no problem, but when using Tesseract1, it is wrong.

### ISSUE THREAD

**Issue by huzhihong** [nguyenq/tess4j#107] opened 2018-07-12 08:26 UTC
When using Tesseract, there is no problem, but when using Tesseract1, it is wrong. But sometimes there's no problem with Tesseract1.the error message: Can not open file "src/main/resources/image/pdf2.tif/pdf.ttf"!

**Comment by nguyenq** [comment] 2018-07-13 12:20
What's your system configuration?

`Tesseract1` API is based on JNA Direct Mapping, which was, at one time, an experimental feature in JNA. It was supposed to behave the same as JNA Interface Mapping, but we observed some differences in certain cases during testing. The one you reported was one of them that we'd seen happened on Linux.

Use `Tesseract` API if the other does not work for you.

**Comment by nguyenq** [comment] 2018-07-13 12:21
Duplicate of Issue https://github.com/nguyenq/tess4j/issues/101.

**Closed** 2018-07-14 12:49 UTC
