### ISSUE TITLE
NullPointerException on Tesseract.dispose

### ISSUE THREAD

**Issue by snow-drop** [nguyenq/tess4j#112] opened 2018-08-21 16:47 UTC
Good day. I'm currently using Tess4j in my simple app and is using the latest 4.2.1 version in Maven repository. I'm currently developing it in Linux and works fine. The issue occurs when I try to run it on Windows.

These are the things in my environment.
Windows 10 64-bit
Microsoft Visual C++ 2010
Microsoft Visual C++ 2012
Microsoft Visual C++ 2015
Microsoft Visual C++ 2017
JDK 8
Tess4j 4.2.1 (also occurs in 4.1.0, Windows 10 64-bit)

```
java.lang.NullPointerException: null
        at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:819) ~[tess4j-4.2.1.jar!/:4.2.1]
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239) ~[tess4j-4.2.1.jar!/:4.2.1]
        at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194) ~[tess4j-4.2.1.jar!/:4.2.1]
```

I've spent almost half a day researching for this issue but still can't find any solution. Can anyone help with this? Thanks :)

**Comment by nguyenq** [comment] 2018-08-21 21:37
A code example would be helpful.

**Comment by snow-drop** [comment] 2018-08-22 04:36
Here is my code example:
```
Tesseract tesseract = new Tesseract();
tesseract.setDataPath("C:\\tesseract"); // parent folder of tessdata
String text = tesseract.doOCR(new File("C:\\tesseract\sample\image.jpg"));
System.out.println(text);
```

**Comment by nguyenq** [comment] 2018-08-22 11:49
If you have a clone copy, please execute the unit test on the command line at the project's root directory:

`mvn test`

**Comment by snow-drop** [comment] 2018-08-29 22:52
I've resorted for CLI-based recognition for the mean time. It would be good if this would be resolved later on. Thanks!

**Comment by nguyenq** [comment] 2018-08-29 23:41
This looks like the same `UnsatisfiedLinkError` [issue](#95) that some developers have been experiencing. Unfortunately, we've never been able to reproduce the issue in order to troubleshoot it. You may want to compile your own custom Tesseract DLL and use it with Tess4J.

**Comment by valerius21** [comment] 2018-08-30 12:41
I've got the same issue, but in a different environment.
Source code:
```
package com.github.valerius21.testing.ocr;

import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract;

import java.io.File;

public class Ocr {
    private static ClassLoader classLoader = Ocr.class.getClassLoader();
    private static File pdfFile = new File(classLoader.getResource("test.pdf").getFile());

    public static void main(String[] args) throws Exception {
        if (pdfFile.exists()) {
            ITesseract tesseract = new Tesseract();

            String result = tesseract.doOCR(pdfFile);
            System.out.println(result);
        }
        else {
            throw new Exception("Inputfile not found");
        }
    }
}
```
No compilation errors, but executional:
```
/usr/lib/jvm/java-10-openjdk/bin/java -javaagent:/home/valerius/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4129.33/lib/idea_rt.jar=44641:/home/valerius/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4129.33/bin -Dfile.encoding=UTF-8 -classpath /home/valerius/code/OCR/out/production/classes:/home/valerius/code/OCR/out/production/resources:/home/valerius/.gradle/caches/modules-2/files-2.1/net.sourceforge.tess4j/tess4j/4.2.1/59a005b5f326eb68a5a52c00647115d6a8cb5017/tess4j-4.2.1.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.ghost4j/ghost4j/1.0.1/a026bc023a623b43df336670ceb00eba355bbc81/ghost4j-1.0.1.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/net.sourceforge.lept4j/lept4j/1.10.0/72153b28e8e1f0391afcc2380c41ac8e73bd599e/lept4j-1.10.0.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/4.1.0/1c12d070e602efd8021891cdd7fd18bc129372d4/jna-4.1.0.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/com.github.jai-imageio/jai-imageio-core/1.4.0/fb6d79b929556362a241b2f65a04e538062f0077/jai-imageio-core-1.4.0.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/pdfbox-tools/2.0.11/6ed2f797da7a73e35bc072ce1bd4dbc3f687ade7/pdfbox-tools-2.0.11.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/pdfbox-debugger/2.0.11/f4f75094a15e40ce1e64ddf6148173cb77274b32/pdfbox-debugger-2.0.11.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/pdfbox/2.0.11/eb7e033d9ae41bd4f0b83681bc5dc01c2488d250/pdfbox-2.0.11.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/jbig2-imageio/3.0.1/94db5a684b9bd72e628449ca60c889013fa95cb2/jbig2-imageio-3.0.1.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.xmlgraphics/xmlgraphics-commons/1.4/52a051c7202449347ab3d717987b5fc2e2a52143/xmlgraphics-commons-1.4.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.6/815893df5f31da2ece4040fe0a12fd44b577afaf/commons-io-2.6.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.jboss/jboss-vfs/3.2.13.Final/d16819de4401488d87664d69a7e820e688759c40/jboss-vfs-3.2.13.Final.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.25/af5364cd6679bfffb114f0dec8a157aaa283b76/jul-to-slf4j-1.7.25.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.25/f8c32b13ff142a513eeb5b6330b1588dcb2c0461/jcl-over-slf4j-1.7.25.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.slf4j/log4j-over-slf4j/1.7.25/a87bb47468f47ee7aabbd54f93e133d4215769c3/log4j-over-slf4j-1.7.25.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.17/5af35056b4d257e4b64b9e8069c0746e8b08629f/log4j-1.2.17.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/commons-beanutils/commons-beanutils/1.9.2/7a87d845ad3a155297e8f67d9008f4c1e5656b71/commons-beanutils-1.9.2.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/com.lowagie/itext/2.1.7/892bfb3e97074a61123b3b2d7caa2db112750864/itext-2.1.7.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/fontbox/2.0.11/b883ca275b4b39f06549e3dbe6b3662a900583e7/fontbox-2.0.11.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.2/4bfc12adfe4842bf07b657f0369c4cb522955686/commons-logging-1.2.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.1.4.GA/90fdefa08d8ad069b86f4ea6033671970459a078/jboss-logging-3.1.4.GA.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.3/864344400c3d4d92dfeb0a305dc87d953677c03c/logback-core-1.2.3.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar:/home/valerius/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.1/761ea405b9b37ced573d2df0d1e3a4e0f9edc668/commons-collections-3.2.1.jar com.github.valerius21.testing.ocr.Ocr
Exception in thread "main" net.sourceforge.tess4j.TesseractException: java.lang.NullPointerException
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at com.github.valerius21.testing.ocr.Ocr.main(Ocr.java:16)
Caused by: java.lang.NullPointerException
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:819)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	... 2 more
14:38:32.512 [main] ERROR net.sourceforge.tess4j.Tesseract - null
java.lang.NullPointerException: null
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:819)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at com.github.valerius21.testing.ocr.Ocr.main(Ocr.java:16)

Process finished with exit code 1
```
OS: Arch Linx
Kernel: 4.18.5-arch1-1-ARCH 
Gradle Version: 4.10
Java:
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

**Comment by Kurtoid** [comment] 2018-11-26 22:00
Definitely a problem with interface mapping, because direct mapping with         
`ITesseract instance = new Tesseract1();`
instead of 
`ITesseract instance = new Tesseract();`
works

**Comment by nguyenq** [comment] 2018-11-27 03:46
@Kurtoid Try updating JNA to the latest version to see if it could help.

**Comment by wenqzhan** [comment] 2018-12-02 05:38
@nguyenq well, something  strange happened....
I am using intellj idea to do some simple apps.... ( Tess4j with the latest 4.3.0 version in Maven repository)
The code I am using is almost exactly the same as OP's
I have two laptops, both running win10 1803 x64
It is very strange that one of my laptops is working fine however the other one is always getting 
java.lang.NullPointerException: null
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:826)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)

**Comment by nguyenq** [comment] 2018-12-14 12:58
The problem stems from the client code being unable to load `libtesseract400.dll` due to CPUs not AVX enabled. This is a duplicate of https://github.com/nguyenq/tess4j/issues/95.

**Closed by nguyenq** 2018-12-14 12:58 UTC

**Comment by kondalarao** [comment] 2021-07-29 11:26
> @Kurtoid Try updating JNA to the latest version to see if it could help.

Helped
