### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zuiailaoda** [nguyenq/tess4j#133] opened 2018-12-18 03:07 UTC
![1](https://user-images.githubusercontent.com/43024499/50129614-c7257380-02b4-11e9-8f67-8588097a70ee.png)
![2](https://user-images.githubusercontent.com/43024499/50129615-c7be0a00-02b4-11e9-9a7c-7cf09e4f7387.png)
![3](https://user-images.githubusercontent.com/43024499/50129616-c7be0a00-02b4-11e9-84e9-573827900c47.png)
![4](https://user-images.githubusercontent.com/43024499/50129629-d86e8000-02b4-11e9-8d2c-435b19156e51.png)

  <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>4.3.0</version>

 VC++ 2015 runtime is installed。

**Comment by nguyenq** [comment] 2018-12-18 03:33
From the output of `tesseract -v`, it indicates that your CPU does not have AVX support. We're trying to produce a `libtesseract400.dll` that will support both AVX and non-AVX CPUs.

Duplicate of https://github.com/nguyenq/tess4j/issues/95.

**Closed by nguyenq** 2018-12-18 03:33 UTC
