### ISSUE TITLE
NullPointerException at net.sourceforge.tess4j.Tesseract.dispose

### ISSUE THREAD

**Issue by madhuse** [nguyenq/tess4j#122] opened 2018-11-01 06:51 UTC
Hi,
I am Reading Scanned pdf file data using tesseractInstance.doOCR(File);
Windows 10 64bit
I have Microsoft visual studio 2015 redistributable 
i am not able to read.
Microsoft visual studio 2017 redistributable is also required for reading i have spent almost one day till now didn't get any answer
Please help me.
Code for reference:

```
ITesseract tessaractInstance = new Tesseract();
List<RenderedFormat> list = new ArrayList<RenderedFormat>();
list.add(RenderedFormat.PDF);
tessaractInstance.setLanguage("eng");
//File tessDataFolder = LoadLibs.extractTessResources("tessdata");
tessaractInstance.setDatapath("D:\\visual studio redistributable\\tess4j-master\\src\\main\\resources\\test1\\tessdata\\");
//System.out.println(tessaractInstance.doOCR(file11));
tessaractInstance.doOCR(file11); 
```

**Comment by nguyenq** [comment] 2018-11-01 12:56
Duplicate of https://github.com/nguyenq/tess4j/issues/112.

**Closed by nguyenq** 2018-11-01 12:56 UTC
