### ISSUE TITLE
Error:Assert failed:in file unicharset.cpp, line 270

### ISSUE THREAD

**Issue by mrvisser** [nguyenq/tess4j#32] opened 2016-02-27 02:01 UTC
I'm getting this error on an image:

`id < this->size():Error:Assert failed:in file unicharset.cpp, line 270`

``` scala
object TesseractTest {

  def main(args: Array[String]): Unit = {
    val tess = new Tesseract
    tess.setDatapath("/usr/local/share/tessdata")
    tess.setLanguage("equ")

    val bi = ImageIO.read(new File("/tmp/test.png"))
    val words = tess.getWords(bi, TessPageIteratorLevel.RIL_WORD).toList
    println(words)
  }
}
```

on MacOSX.

I don't get this error when running tesseract on the command line:

```
$ tesseract /tmp/test.png out -l equ hocr
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
Warning in pixReadMemPng: work-around: writing to a temp file
OSD: Weak margin (0.66), horiz textlines, not CJK: Don't rotate.
```

<img width="306" alt="screen shot 2016-02-26 at 5 28 18 pm" src="https://cloud.githubusercontent.com/assets/102265/13370054/c2bae2a6-dcb2-11e5-8734-58f4babef5d3.png">

As you can see, I'm trying to use the equations training data. It seems this error always happens when trying to use that training data. I have it loaded in my `/usr/local/share/tessdata/equ.trainingdata` from `https://github.com/tesseract-ocr/tessdata/blob/master/equ.traineddata`. I have not seen this error on other languages.

Any idea what's happening?

**Comment by nguyenq** [comment] 2016-02-27 04:07
I have no problem with the image. Can you try with data path set to `"/usr/local/share/"`?

**Comment by mrvisser** [comment] 2016-02-27 05:33
I just tried it and it suffers from the same issue. What version of tesseract are you running?

**Comment by nguyenq** [comment] 2016-02-27 12:39
I use tess4j-3.0, which wraps Tesseract 3.04. I do not have appropriate fonts to display the output:

∫⋅⊅↗∣⋅∣⇅⊖⊅↕⊳
∫⋅⋯⊄≴⊖−⋝∁⊅↕⊳
⋮−⇋∏ ⋮ ∫⋅⊅⊖⋅↕⊺⋚⊅↕⋅
∫⋅⋯∣∁⊖⋮⋃↗⋯⊅↕⋅
∫⋅⊅⊖⊺⋅⋯−⋝⊅↕∙

⋅∄∁⇈∽⊈⊃∤∏⋅⊄↕−⋝⊖−⋝⊅↕⊳

**Comment by 4F2E4A2E** [comment] 2016-03-01 22:29
@mrvisser i guess this is not tess4h itself related and you are better of at https://github.com/tesseract-ocr/tesseract

**Comment by mrvisser** [comment] 2016-03-03 23:52
Thanks for the feedback. If I run it from the tesseract command line it works fine, which is why I'm not sure they could do much about it.

**Comment by 4F2E4A2E** [comment] 2016-03-04 22:02
You you are using scala right? Which JDK Version exactly?

**Comment by mrvisser** [comment] 2016-03-04 22:27
JDK_1.8.0_65

**Comment by nguyenq** [comment] 2018-01-18 21:56
This is a very old report. We're not sure if it was a real problem. We're closing it as we could not reproduce the error. You can reopen if it's still an issue.

**Closed by nguyenq** 2018-01-18 21:56 UTC
Labels: question
