### ISSUE TITLE
!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209

### ISSUE THREAD

**Issue by abhilash29** [nguyenq/tess4j#135] opened 2018-12-27 07:22 UTC
![abhilashsathe_ _-bash_ _80x24](https://user-images.githubusercontent.com/1309199/50470399-4f52f980-09d6-11e9-9a22-6bf35a5405c8.png)
![item-0_and_item-0_and_applebluetoothextra](https://user-images.githubusercontent.com/1309199/50470400-4f52f980-09d6-11e9-9288-02a5c098cd9a.png)

**Comment by nguyenq** [comment] 2019-01-10 01:15
And you launched your IDE from that command line?

Anyway, this is a duplicate of Issue #105 and will be closed accordingly.

**Closed** 2019-01-21 15:42 UTC
