### ISSUE TITLE
Tess4j output differs from Tesseract cli output

### ISSUE THREAD

**Issue by brucardoso2** [nguyenq/tess4j#14] opened 2015-02-12 22:02 UTC
Here are the steps
1. `git clone https://github.com/nguyenq/tess4j.git`
2. `cd tess4j`
3. `mvn clean package` (it will create both shaded and normal jar)
4. Install the normal jar into local repository 
    `mvn install:install-file -Dfile=target/tess4j-2.0.0-SNAPSHOT.jar -DpomFile=pom.xml `

I created a simple repository to ease your testing
5. `git clone https://github.com/brucardoso2/tess4jtest.git`
6. `mvn clean package` (it will create both shaded and normal jar)

Now run the shaded jar with this image: https://www.dropbox.com/s/hhas9bddxpiaj97/workingimage001.png?dl=0
7. `java -jar target/ShadedMaven-1.0-SNAPSHOT-shaded.jar workingimage001.png`

It should output 
```
X
Y
Y
```

But tess4j outputs "Empty page !!"

------------------------------
Tesseract version used:
```
$ tesseract --version
tesseract 3.02
 leptonica-1.68 (Mar 14 2011, 10:43:03) [MSC v.1500 LIB Release 32 bit]
  libgif 4.1.6 : libjpeg 8c : libpng 1.4.3 : libtiff 3.9.4 : zlib 1.2.5
```

**Comment by nguyenq** [comment] 2015-02-13 00:12
They employ different methods, which could result in variations in output: Tess 3.02 uses `GetOCRText` whereas 3.03 uses the new `ResultRenderer` API.

**Comment by 4F2E4A2E** [comment] 2015-06-06 05:35
Step 4: mvn install will install your package into the local repo, no need to explicitly tell it to.

**Comment by 4F2E4A2E** [comment] 2015-06-06 05:50
Hello there! I think @nguyenq did answer your question and the problem is solved right? Do you need further help? Don't need to create an extra Repo, just post a unit test.

**Comment by 4F2E4A2E** [comment] 2015-06-06 05:52
And i hope the test files you are posting aren't for internal use only or classified ^^

**Comment by 4F2E4A2E** [comment] 2015-06-06 07:05
Don't need to use dropbox you can also upload a files here at this issue...
I just did notice, that in your Main
```java
public static void main(String[] args) {
        if(args.length < 1) {
            System.out.println("Usage: ShadedMaven <inputImage>");
            System.exit(1);
        }

        File imageFile = new File(args[0]);
        Tesseract instance = Tesseract.getInstance();

        //In case you don't have your own tessdata, let it also be extracted for you
        File tessDataFolder = LoadLibs.extractTessResources("tessdata");

        //Set the tessdata path
        instance.setDatapath(tessDataFolder.getAbsolutePath());

        try {
            Rectangle rect = new Rectangle(305,681,146,2073); // Document uzn
            String result = instance.doOCR(imageFile, rect);
            System.out.println(result);
        } catch (TesseractException e) {
            System.err.println(e.getMessage());
        }
    }
```
you are passing a rectangle instead of using uzn files.

Please note that you also can make use of uzn files and tees4j will recognize it for you if the uzn file has the same name as the image beeing passed: [/src/test/java/net/sourceforge/tess4j/TesseractTest.java#L99](https://github.com/nguyenq/tess4j/blob/0e334ef376f94a28855a7773681d42d69912ee04/src/test/java/net/sourceforge/tess4j/TesseractTest.java#L99)

Can i close this issue?

**Closed** 2016-03-22 05:34 UTC
Labels: question
