### ISSUE TITLE
Tess4J 4.0.0 java.lang.UnsatisfiedLinkError: The specified module could not be found

### ISSUE THREAD

**Issue by kirans13** [nguyenq/tess4j#100] opened 2018-06-26 08:27 UTC
Downloading and using tessData-best for tesseract-ocr github repository improved my accuracy for english on Tess4j 3.8.4 significantly. But to use that trainedData for other languages i had to upgrade to Tess4J 4.0.0. But When I did that its giving me following error on this line

```
TessBaseAPI api = TessAPI1.TessBaseAPICreate();


Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.
    at com.sun.jna.Native.open(Native Method)
    at com.sun.jna.Native.open(Native.java:1759)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:260)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Native.register(Native.java:1396)
    at com.sun.jna.Native.register(Native.java:1156)
    at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)
    at OCR.confidenceWord(OCR.java:106)
    at OCR.processImg(OCR.java:381)
    at test.main(test.java:10)
```

I have 64-bit windows 8.1 running on my machine with 64-bit JVM. I have VC++ 2015 redistributable installed. I checked in dependency walker and no dll seems to be missing.By setting system property "jna.debug.load" to "true", I can see it properly looks for and gets "libtesseract400" at temp folder. Has anyone been able to solve this error?

**Comment by nguyenq** [comment] 2018-06-30 00:59
Duplicate of Issue #95.

**Closed by nguyenq** 2018-06-30 00:59 UTC
