### ISSUE TITLE
BUG in new release (tess4j 4.0.0) (UnsatisfiedlinkError libtesseract400.dll)

### ISSUE THREAD

**Issue by garzy** [nguyenq/tess4j#91] opened 2018-05-01 12:11 UTC
With tess4j 4.0 version the lib can't auto load libtesseract400.dll that is inside the jar for something extrange reason that I don't know. I rollback to 3.4.7 and everything it's OK.

I'm launching over Microsoft Windows 10 Pro x64 (Dist: April 2018)

I'm installed the latest vc_redist 2015 x86 and x64 and the problem still here.

Please fix when you can, I can work with previous version.

Thanks!

**Comment by nguyenq** [comment] 2018-05-01 14:32
We're unable to reproduce your issue. We develop and test on Win10, JDK 1.8.0_171 both 32- and 64-bit, and VC++ 2017.

Please try install Microsoft Visual C++ Redistributable for Visual Studio 2017. The link is at the bottom of https://www.visualstudio.com/downloads/ page.

**Comment by nguyenq** [comment] 2018-05-27 01:26
Do you still experience this issue with the latest release?

**Comment by garzy** [comment] 2018-05-27 12:02
At this moment I contiue with the previous 3.x version, the next week I
will upgrade version and then reply you again, thanks

**Comment by garzy** [comment] 2018-06-03 23:09
Don't work, I've installed redist 2007 x64 and x32. I've tested with java 8 x84 and java 9 x64 and didn't work. I'm back to 3.x again. Thanks

**Comment by nguyenq** [comment] 2018-06-04 00:31
Duplicate of #95. Let's continue discussions on that issue.

**Closed by nguyenq** 2018-06-04 00:31 UTC
