### ISSUE TITLE
Invalid calling convention 63  (Ghostscript, Tess4J, Ghost4J) 

### ISSUE THREAD

**Issue by bliss-pelete** [nguyenq/tess4j#35] opened 2016-05-02 16:37 UTC
Hello, 

I'm using tess4j to make a webapp that scans PDF bills or pictures to extract a certain reference number. I developed the webapp on Windows where everything is working fine so far ( although i have some image pre-processing to implement). Since the webapp will be running on a Linux server i'm running some test on  a Debian system. I have compiled tesseract libraries and leptonica and also installed ghostscript and the required libraries. When testing an image i get the correct results but when it comes to testing pdf I have an invalid calling convention 63 error. I've browsed on various post related to this subject and applied the suggested solutions. 
My system: 
Debian 8 Jessie 
Tesseract 3.04.01 
Leptonica 1.72 
The webapp is running with Tomcat 8.0.33 

**What I have done so far to fix this issue: **
 
- Switched the JNA from 4.2.2 to 4.1.0 in the provided libs for Ghost4j
https://github.com/zippy1978/ghost4j/issues/44

- Switched Ghostscript version from 9.18 to 9.16 according to this post
https://github.com/nguyenq/tess4j/issues/30#issuecomment-185533296

Regardless of all that, the issue persists. So I would appreciate some pointers on how to fix this issue. Is it related to Debian ? Is there something I have done wrong ? Maybe there's a library I failed to install. The ocr works for pictures so my suspicion is that the problem is linked to PDF conversion. 

The next option I will try is to make the tests on a CentOS system. But I thought that if I could get it running on Debian it should be running anywhere. I'd like to point out that I'm a student so I apologize if I seem unclear or lack some technicalities. This my internship subject so I'm doing my best to get it working. If needed I'll provided additional information. 

Thank you 

Stacktrace
`
type Exception report

message Request processing failed; nested exception is java.lang.IllegalArgumentException: Invalid calling convention 63

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Invalid calling convention 63
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:980)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.IllegalArgumentException: Invalid calling convention 63
	com.sun.jna.Native.createNativeCallback(Native Method)
	com.sun.jna.CallbackReference.<init>(CallbackReference.java:239)
	com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:413)
	com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:395)
	com.sun.jna.Function.convertArgument(Function.java:541)
	com.sun.jna.Function.invoke(Function.java:305)
	com.sun.jna.Library$Handler.invoke(Library.java:236)
	com.sun.proxy.$Proxy49.gsapi_set_stdio(Unknown Source)
	org.ghost4j.Ghostscript.initialize(Ghostscript.java:323)
	net.sourceforge.tess4j.util.PdfUtilities.convertPdf2Png(PdfUtilities.java:103)
	fr.ocr.jouleye.analysis.FileAnalyzer.Analyse(FileAnalyzer.java:67)
	fr.ocr.jouleye.controller.FileUploadController.showPDL(FileUploadController.java:112)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.33 logs.`

**Comment by nguyenq** [comment] 2016-05-02 23:49
In one of the posts over Ghost4J Issue#44, @LinhTH mentioned he had found the root cause of the issue. Hope he can share with us the solution. I'll see if I could find time this weekend to investigate this issue on Ubuntu. There's no guarantee finding the cause, and solution, though.

If this is a pressing matter, I would suggest you convert, outside of Tess4J, the PDF to images using another tool, PDFBox, for instance.

**Comment by bliss-pelete** [comment] 2016-05-03 17:35
Thanks for the reply. I still have around a month or so to work on this project. So there's no rush. But any pointer that can somehow enlighten the question would be very much appreciated. I will test it out on Cent OS to see if it works there without any issue, and if not I'll change the converter tool. I will keep you update on any development.

**Comment by nguyenq** [comment] 2016-05-09 02:58
Just to let you know that I've been able to reproduce the error running Maven test on the trunk code against stock Tesseract in Ubuntu 16.04 with JDK1.8.0_92. Will try to get to the bottom of the problem.

**Comment by bliss-pelete** [comment] 2016-05-09 07:50
Alright thanks for the feedback.

**Comment by nguyenq** [comment] 2016-05-10 01:19
After I dropped the JNA version down to 4.1.0, the tests pertaining to PDF and Ghost4J passed. This concurs with a finding described by another developer in https://github.com/zippy1978/ghost4j/issues/44.

**Comment by bliss-pelete** [comment] 2016-05-12 16:27
Hello, 

I have tested the webapp on the server which is running on CentOS and I did not have any issue whatsoever neither with Ghostscript or Tess4J. Everything seems to be running smoothly which is great. 
I will be doing my other test on that plateform since all is good on that side. I'll try and get it working on Debian just to see if I can find a solution.  

I have another question regarding Tess4J. Let me know if I should open another ticket for this. How to improving tesseract processing speed without decreasing accuracy ? 

Thanks a lot for your input. :)

**Comment by nguyenq** [comment] 2016-05-16 01:17
3.2.0 has just been released to address the issue.

As to the Tesseract performance question, I think it should be directed at users and developers in [Tesseract Forum](https://groups.google.com/forum/#!forum/tesseract-ocr).

As far as Java is concerned, you can use threading to parallel process large volume of images. You may also want to cut down on the number of expensive native init & dispose processes. See the posts below.

https://sourceforge.net/p/tess4j/discussion/1202293/thread/4562eccb/
https://sourceforge.net/p/tess4j/discussion/1202294/thread/d32bd579/

**Comment by nguyenq** [comment] 2016-07-10 23:26
Fixed by downgrading JNA (commit https://github.com/nguyenq/tess4j/commit/7ea11dd991b02892db335248cfe380ea32aaabf7).

**Closed by nguyenq** 2016-07-10 23:26 UTC

**Comment by mathiasconradt** [comment] 2016-11-01 14:16
I still get this issue in 3.2.1 on Linux. http://stackoverflow.com/questions/40361873/tess4j-invalid-calling-convention-63-despite-correct-versions

**Comment by nguyenq** [comment] 2016-11-01 23:24
Make sure that you use `jna-4.1.0` version.

**Comment by mathiasconradt** [comment] 2016-11-02 07:40
Ok, I didn't explicitly reference JNA anywhere in my project pom, I thought this is all done in Tess4J 3.2.1 and it's pom.xml. I added JNA 4.1.0 in my pom.xml now as well and this seems to solve the problem.

**Comment by DanielMalmgren** [comment] 2018-05-04 10:15
Hi. Sorry to throw comments into this old issue, but did anyone ever go for the root cause of this? I'm having the exact same problem in a completely different project, that any JNA above 4.1.0 produces "Invalid calling convention 63". Tried with 4.5.1 which is currently the latest version and the problem is still there. Is it a problem in JNA itself and if so was it reported anywhere?

**Comment by nguyenq** [comment] 2018-05-04 12:11
Looks like noone has been tackling the issue. If someone's willing...

https://github.com/zippy1978/ghost4j/issues/57

**Comment by DanielMalmgren** [comment] 2018-05-04 12:25
I actually did some more digging myself. It seems the “Invalid calling convention” is something JNA spits out when wrong ABI is used. I'm on an 64 bit arm processor, running 32-bit JVM. This works fine in JNA up to 4.1.0, but after that they introduced support for arm64. Seems it then tries to use the 64-bit ABI although it's running in 32 bits or something like that. I guess that's the case for the others with this problem as well, being on ARMv8 architecture but running 32-bit JVM?

**Comment by nguyenq** [comment] 2018-05-04 13:00
The problem seemed to occur with any CPU/JVM on Linux. It would be easier to fix ghost4j, but I suspect it was something that was introduced into JNA after 4.1.0.

If Ghostscript cannot be used, there's PDFBox available via `System.setProperty(PdfUtilities.PDF_LIBRARY, PdfUtilities.PDFBOX);` setting, but you would have to absorb a performance hit in PDF conversion.

**Comment by nguyenq** [comment] 2018-05-04 13:33
FYI, JNA 4.2.0 contains these constant value definitions:

`ALT_CONVENTION	63`
`OPTION_CALLING_CONVENTION	"calling-convention"`

https://java-native-access.github.io/jna/4.2.0/constant-values.html

**Comment by sandye** [comment] 2020-05-26 12:24
I just fixed this issue by changing "com.sun.jna.win32.StdCallLibrary.StdCallCallback" to "com.sun.jna.Callback" in GhostscriptLibrary.java.. I am using the app in linux and macos

**Comment by nguyenq** [comment] 2020-05-26 17:09
I vaguely recall that I tested a similar change a while back. While the fix worked for Linux, it broke for Windows.
