### ISSUE TITLE
java.lang.UnsatisfiedLinkError : Error Looking Up function TessBaseAPICreate : The specified procedure can not be found. Tess4j 5.8.0

### ISSUE THREAD

**Issue by sumamarpuri** [nguyenq/tess4j#250] opened 2023-07-31 12:07 UTC
java.lang.UnsatisfiedLinkError : Error Looking Up function TessBaseAPICreate : The specified procedure can not be found

I'm unable to resolve this error in Windows 10. Please help me to resolve this issue.

I'm using tesseract 5.3.1 and Tess4j 5.8.0. tried with different versions and none of them worked.

**Comment by nguyenq** [comment] 2023-08-06 15:42
@sumamarpuri Did you install the required VC++ Runtime?

**Comment by sumamarpuri** [comment] 2023-08-07 14:52
Hi, I have Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31326 installed in my machine

**Comment by RankesGitHub** [comment] 2023-11-14 08:58
+1

**Comment by nguyenq** [comment] 2024-03-02 19:26
@sumamarpuri @RankesGitHub Can you test with the latest version in the repo?

**Comment by nguyenq** [comment] 2024-03-08 04:10
Let's close this issue as it's a duplicate of https://github.com/nguyenq/tess4j/issues/258 or vice versa. We can continue discussion over there.

**Closed by nguyenq** 2024-03-08 04:10 UTC
